### ISSUE TITLE
Non-static method OnlyofficeSettingsFormBuilder::*() cannot be called statically 

### ISSUE THREAD

**Issue by ywarnier** [ONLYOFFICE/onlyoffice-chamilo#38]
With release 1.4 on PHP 7.4, I have a series of Fatal errors appearing (not sure of the environment in which you are testing):
```
PHP Fatal error:  Uncaught Error: Non-static method OnlyofficeSettingsFormBuilder::buildSettingsForm() cannot be called statically
PHP Fatal error:  Uncaught Error: Non-static method OnlyofficeSettingsFormBuilder::buildTemplate() cannot be called statically
PHP Fatal error:  Uncaught Error: Non-static method OnlyofficeSettingsFormBuilder::validateSettingsForm() cannot be called statically
PHP Fatal error:  Uncaught Error: Non-static method OnlyofficeSettingsFormBuilder::displayError() cannot be called statically
```

**Comment by ywarnier** [comment]
This is fixed by prefixing the `function` term by `static` in onlyoffice/lib/onlyofficeSettingsFormBuilder.php, but I'm not yet sure this is fixed by *just* updating those 4 ones (I'm having other issues).

**Comment by LinneyS** [comment]
Thanks for your warning
we [fixed it](https://github.com/ONLYOFFICE/onlyoffice-chamilo/commit/5494eed074beda41375363531c76a7cb11a66e00)
Can you check this using the develop branch?

**Comment by LinneyS** [comment]
[Artifact](https://github.com/ONLYOFFICE/onlyoffice-chamilo/actions/runs/11364999153)

**Comment by ywarnier** [comment]
With the current "develop" branch, I get this now:
```
PHP Fatal error:  Uncaught Error: 
Using $this when not in object context in /var/www/host/www/plugin/onlyoffice/lib/onlyofficeAppRequests.php:59
Stack trace:
#0 /var/www/host/www/plugin/onlyoffice/lib/onlyofficeAppRequests.php(32): OnlyofficeAppRequests::createTempFile()
#1 /var/www/host/www/plugin/onlyoffice/lib/onlyofficeSettingsFormBuilder.php(97): OnlyofficeAppRequests->__construct()
#2 /var/www/host/www/plugin/onlyoffice/plugin.php(30): OnlyofficeSettingsFormBuilder::validateSettingsForm()
#3 /var/www/host/www/main/inc/lib/plugin.lib.php(563): require('...')
#4 /var/www/host/www/main/admin/configure_plugin.php(17): AppPlugin->getPluginInfo()
#5 {main}
  thrown in /var/www/host/www/plugin/onlyoffice/lib/onlyofficeAppRequests.php on line 59
```

**Comment by LinneyS** [comment]
0e7f30da7637d76496193ec3a9cb7da5884483be

**Comment by ywarnier** [comment]
Fixed now in the develop branch. Thanks.
